/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface ElementData {
  symbol: string;
  name: string;
  atomicNumber: number;
  atomicMass: number;
  category: string;
  x: number; // Column (1-18)
  y: number; // Row (1-7, plus lanthanides/actinides)
}

export const ELEMENTS: ElementData[] = [
  { symbol: "H", name: "Hidrogênio", atomicNumber: 1, atomicMass: 1.008, category: "nonmetal", x: 1, y: 1 },
  { symbol: "He", name: "Hélio", atomicNumber: 2, atomicMass: 4.0026, category: "noble-gas", x: 18, y: 1 },
  { symbol: "Li", name: "Lítio", atomicNumber: 3, atomicMass: 6.94, category: "alkali-metal", x: 1, y: 2 },
  { symbol: "Be", name: "Berílio", atomicNumber: 4, atomicMass: 9.0122, category: "alkaline-earth", x: 2, y: 2 },
  { symbol: "B", name: "Boro", atomicNumber: 5, atomicMass: 10.81, category: "metalloid", x: 13, y: 2 },
  { symbol: "C", name: "Carbono", atomicNumber: 6, atomicMass: 12.011, category: "nonmetal", x: 14, y: 2 },
  { symbol: "N", name: "Nitrogênio", atomicNumber: 7, atomicMass: 14.007, category: "nonmetal", x: 15, y: 2 },
  { symbol: "O", name: "Oxigênio", atomicNumber: 8, atomicMass: 15.999, category: "nonmetal", x: 16, y: 2 },
  { symbol: "F", name: "Flúor", atomicNumber: 9, atomicMass: 18.998, category: "halogen", x: 17, y: 2 },
  { symbol: "Ne", name: "Neônio", atomicNumber: 10, atomicMass: 20.180, category: "noble-gas", x: 18, y: 2 },
  { symbol: "Na", name: "Sódio", atomicNumber: 11, atomicMass: 22.990, category: "alkali-metal", x: 1, y: 3 },
  { symbol: "Mg", name: "Magnésio", atomicNumber: 12, atomicMass: 24.305, category: "alkaline-earth", x: 2, y: 3 },
  { symbol: "Al", name: "Alumínio", atomicNumber: 13, atomicMass: 26.982, category: "post-transition", x: 13, y: 3 },
  { symbol: "Si", name: "Silício", atomicNumber: 14, atomicMass: 28.085, category: "metalloid", x: 14, y: 3 },
  { symbol: "P", name: "Fósforo", atomicNumber: 15, atomicMass: 30.974, category: "nonmetal", x: 15, y: 3 },
  { symbol: "S", name: "Enxofre", atomicNumber: 16, atomicMass: 32.06, category: "nonmetal", x: 16, y: 3 },
  { symbol: "Cl", name: "Cloro", atomicNumber: 17, atomicMass: 35.45, category: "halogen", x: 17, y: 3 },
  { symbol: "Ar", name: "Argônio", atomicNumber: 18, atomicMass: 39.948, category: "noble-gas", x: 18, y: 3 },
  { symbol: "K", name: "Potássio", atomicNumber: 19, atomicMass: 39.098, category: "alkali-metal", x: 1, y: 4 },
  { symbol: "Ca", name: "Cálcio", atomicNumber: 20, atomicMass: 40.078, category: "alkaline-earth", x: 2, y: 4 },
  { symbol: "Sc", name: "Escândio", atomicNumber: 21, atomicMass: 44.956, category: "transition-metal", x: 3, y: 4 },
  { symbol: "Ti", name: "Titânio", atomicNumber: 22, atomicMass: 47.867, category: "transition-metal", x: 4, y: 4 },
  { symbol: "V", name: "Vanádio", atomicNumber: 23, atomicMass: 50.942, category: "transition-metal", x: 5, y: 4 },
  { symbol: "Cr", name: "Cromo", atomicNumber: 24, atomicMass: 51.996, category: "transition-metal", x: 6, y: 4 },
  { symbol: "Mn", name: "Manganês", atomicNumber: 25, atomicMass: 54.938, category: "transition-metal", x: 7, y: 4 },
  { symbol: "Fe", name: "Ferro", atomicNumber: 26, atomicMass: 55.845, category: "transition-metal", x: 8, y: 4 },
  { symbol: "Co", name: "Cobalto", atomicNumber: 27, atomicMass: 58.933, category: "transition-metal", x: 9, y: 4 },
  { symbol: "Ni", name: "Níquel", atomicNumber: 28, atomicMass: 58.693, category: "transition-metal", x: 10, y: 4 },
  { symbol: "Cu", name: "Cobre", atomicNumber: 29, atomicMass: 63.546, category: "transition-metal", x: 11, y: 4 },
  { symbol: "Zn", name: "Zinco", atomicNumber: 30, atomicMass: 65.38, category: "transition-metal", x: 12, y: 4 },
  { symbol: "Ga", name: "Gálio", atomicNumber: 31, atomicMass: 69.723, category: "post-transition", x: 13, y: 4 },
  { symbol: "Ge", name: "Germânio", atomicNumber: 32, atomicMass: 72.63, category: "metalloid", x: 14, y: 4 },
  { symbol: "As", name: "Arsênio", atomicNumber: 33, atomicMass: 74.922, category: "metalloid", x: 15, y: 4 },
  { symbol: "Se", name: "Selênio", atomicNumber: 34, atomicMass: 78.971, category: "nonmetal", x: 16, y: 4 },
  { symbol: "Br", name: "Bromo", atomicNumber: 35, atomicMass: 79.904, category: "halogen", x: 17, y: 4 },
  { symbol: "Kr", name: "Criptônio", atomicNumber: 36, atomicMass: 83.798, category: "noble-gas", x: 18, y: 4 },
  { symbol: "Rb", name: "Rubídio", atomicNumber: 37, atomicMass: 85.468, category: "alkali-metal", x: 1, y: 5 },
  { symbol: "Sr", name: "Estrôncio", atomicNumber: 38, atomicMass: 87.62, category: "alkaline-earth", x: 2, y: 5 },
  { symbol: "Y", name: "Ítrio", atomicNumber: 39, atomicMass: 88.906, category: "transition-metal", x: 3, y: 5 },
  { symbol: "Zr", name: "Zircônio", atomicNumber: 40, atomicMass: 91.224, category: "transition-metal", x: 4, y: 5 },
  { symbol: "Nb", name: "Nióbio", atomicNumber: 41, atomicMass: 92.906, category: "transition-metal", x: 5, y: 5 },
  { symbol: "Mo", name: "Molibdênio", atomicNumber: 42, atomicMass: 95.95, category: "transition-metal", x: 6, y: 5 },
  { symbol: "Tc", name: "Tecnécio", atomicNumber: 43, atomicMass: 98, category: "transition-metal", x: 7, y: 5 },
  { symbol: "Ru", name: "Rutênio", atomicNumber: 44, atomicMass: 101.07, category: "transition-metal", x: 8, y: 5 },
  { symbol: "Rh", name: "Ródio", atomicNumber: 45, atomicMass: 102.91, category: "transition-metal", x: 9, y: 5 },
  { symbol: "Pd", name: "Paládio", atomicNumber: 46, atomicMass: 106.42, category: "transition-metal", x: 10, y: 5 },
  { symbol: "Ag", name: "Prata", atomicNumber: 47, atomicMass: 107.87, category: "transition-metal", x: 11, y: 5 },
  { symbol: "Cd", name: "Cádmio", atomicNumber: 48, atomicMass: 112.41, category: "transition-metal", x: 12, y: 5 },
  { symbol: "In", name: "Índio", atomicNumber: 49, atomicMass: 114.82, category: "post-transition", x: 13, y: 5 },
  { symbol: "Sn", name: "Estanho", atomicNumber: 50, atomicMass: 118.71, category: "post-transition", x: 14, y: 5 },
  { symbol: "Sb", name: "Antimônio", atomicNumber: 51, atomicMass: 121.76, category: "metalloid", x: 15, y: 5 },
  { symbol: "Te", name: "Telúrio", atomicNumber: 52, atomicMass: 127.60, category: "metalloid", x: 16, y: 5 },
  { symbol: "I", name: "Iodo", atomicNumber: 53, atomicMass: 126.90, category: "halogen", x: 17, y: 5 },
  { symbol: "Xe", name: "Xenônio", atomicNumber: 54, atomicMass: 131.29, category: "noble-gas", x: 18, y: 5 },
  { symbol: "Cs", name: "Césio", atomicNumber: 55, atomicMass: 132.91, category: "alkali-metal", x: 1, y: 6 },
  { symbol: "Ba", name: "Bário", atomicNumber: 56, atomicMass: 137.33, category: "alkaline-earth", x: 2, y: 6 },
  { symbol: "La", name: "Lantânio", atomicNumber: 57, atomicMass: 138.91, category: "lanthanide", x: 4, y: 9 },
  { symbol: "Ce", name: "Cério", atomicNumber: 58, atomicMass: 140.12, category: "lanthanide", x: 5, y: 9 },
  { symbol: "Pr", name: "Praseodímio", atomicNumber: 59, atomicMass: 140.91, category: "lanthanide", x: 6, y: 9 },
  { symbol: "Nd", name: "Neodímio", atomicNumber: 60, atomicMass: 144.24, category: "lanthanide", x: 7, y: 9 },
  { symbol: "Pm", name: "Promécio", atomicNumber: 61, atomicMass: 145, category: "lanthanide", x: 8, y: 9 },
  { symbol: "Sm", name: "Samário", atomicNumber: 62, atomicMass: 150.36, category: "lanthanide", x: 9, y: 9 },
  { symbol: "Eu", name: "Európio", atomicNumber: 63, atomicMass: 151.96, category: "lanthanide", x: 10, y: 9 },
  { symbol: "Gd", name: "Gadolínio", atomicNumber: 64, atomicMass: 157.25, category: "lanthanide", x: 11, y: 9 },
  { symbol: "Tb", name: "Térbio", atomicNumber: 65, atomicMass: 158.93, category: "lanthanide", x: 12, y: 9 },
  { symbol: "Dy", name: "Disprósio", atomicNumber: 66, atomicMass: 162.50, category: "lanthanide", x: 13, y: 9 },
  { symbol: "Ho", name: "Hólmio", atomicNumber: 67, atomicMass: 164.93, category: "lanthanide", x: 14, y: 9 },
  { symbol: "Er", name: "Érbio", atomicNumber: 68, atomicMass: 167.26, category: "lanthanide", x: 15, y: 9 },
  { symbol: "Tm", name: "Túlio", atomicNumber: 69, atomicMass: 168.93, category: "lanthanide", x: 16, y: 9 },
  { symbol: "Yb", name: "Itérbio", atomicNumber: 70, atomicMass: 173.05, category: "lanthanide", x: 17, y: 9 },
  { symbol: "Lu", name: "Lutécio", atomicNumber: 71, atomicMass: 174.97, category: "lanthanide", x: 18, y: 9 },
  { symbol: "Hf", name: "Háfnio", atomicNumber: 72, atomicMass: 178.49, category: "transition-metal", x: 4, y: 6 },
  { symbol: "Ta", name: "Tântalo", atomicNumber: 73, atomicMass: 180.95, category: "transition-metal", x: 5, y: 6 },
  { symbol: "W", name: "Tungstênio", atomicNumber: 74, atomicMass: 183.84, category: "transition-metal", x: 6, y: 6 },
  { symbol: "Re", name: "Rênio", atomicNumber: 75, atomicMass: 186.21, category: "transition-metal", x: 7, y: 6 },
  { symbol: "Os", name: "Ósmio", atomicNumber: 76, atomicMass: 190.23, category: "transition-metal", x: 8, y: 6 },
  { symbol: "Ir", name: "Irídio", atomicNumber: 77, atomicMass: 192.22, category: "transition-metal", x: 9, y: 6 },
  { symbol: "Pt", name: "Platina", atomicNumber: 78, atomicMass: 195.08, category: "transition-metal", x: 10, y: 6 },
  { symbol: "Au", name: "Ouro", atomicNumber: 79, atomicMass: 196.97, category: "transition-metal", x: 11, y: 6 },
  { symbol: "Hg", name: "Mercúrio", atomicNumber: 80, atomicMass: 200.59, category: "transition-metal", x: 12, y: 6 },
  { symbol: "Tl", name: "Tálio", atomicNumber: 81, atomicMass: 204.38, category: "post-transition", x: 13, y: 6 },
  { symbol: "Pb", name: "Chumbo", atomicNumber: 82, atomicMass: 207.2, category: "post-transition", x: 14, y: 6 },
  { symbol: "Bi", name: "Bismuto", atomicNumber: 83, atomicMass: 208.98, category: "post-transition", x: 15, y: 6 },
  { symbol: "Po", name: "Polônio", atomicNumber: 84, atomicMass: 209, category: "post-transition", x: 16, y: 6 },
  { symbol: "At", name: "Astato", atomicNumber: 85, atomicMass: 210, category: "halogen", x: 17, y: 6 },
  { symbol: "Rn", name: "Radônio", atomicNumber: 86, atomicMass: 222, category: "noble-gas", x: 18, y: 6 },
  { symbol: "Fr", name: "Frâncio", atomicNumber: 87, atomicMass: 223, category: "alkali-metal", x: 1, y: 7 },
  { symbol: "Ra", name: "Rádio", atomicNumber: 88, atomicMass: 226, category: "alkaline-earth", x: 2, y: 7 },
  { symbol: "Ac", name: "Actínio", atomicNumber: 89, atomicMass: 227, category: "actinide", x: 4, y: 10 },
  { symbol: "Th", name: "Tório", atomicNumber: 90, atomicMass: 232.04, category: "actinide", x: 5, y: 10 },
  { symbol: "Pa", name: "Protactínio", atomicNumber: 91, atomicMass: 231.04, category: "actinide", x: 6, y: 10 },
  { symbol: "U", name: "Urânio", atomicNumber: 92, atomicMass: 238.03, category: "actinide", x: 7, y: 10 },
  { symbol: "Np", name: "Netúnio", atomicNumber: 93, atomicMass: 237, category: "actinide", x: 8, y: 10 },
  { symbol: "Pu", name: "Plutônio", atomicNumber: 94, atomicMass: 244, category: "actinide", x: 9, y: 10 },
  { symbol: "Am", name: "Amerício", atomicNumber: 95, atomicMass: 243, category: "actinide", x: 10, y: 10 },
  { symbol: "Cm", name: "Cúrio", atomicNumber: 96, atomicMass: 247, category: "actinide", x: 11, y: 10 },
  { symbol: "Bk", name: "Berquélio", atomicNumber: 97, atomicMass: 247, category: "actinide", x: 12, y: 10 },
  { symbol: "Cf", name: "Califórnio", atomicNumber: 98, atomicMass: 251, category: "actinide", x: 13, y: 10 },
  { symbol: "Es", name: "Enstênio", atomicNumber: 99, atomicMass: 252, category: "actinide", x: 14, y: 10 },
  { symbol: "Fm", name: "Férmio", atomicNumber: 100, atomicMass: 257, category: "actinide", x: 15, y: 10 },
  { symbol: "Md", name: "Mendelévio", atomicNumber: 101, atomicMass: 258, category: "actinide", x: 16, y: 10 },
  { symbol: "No", name: "Nobélio", atomicNumber: 102, atomicMass: 259, category: "actinide", x: 17, y: 10 },
  { symbol: "Lr", name: "Laurêncio", atomicNumber: 103, atomicMass: 262, category: "actinide", x: 18, y: 10 },
  { symbol: "Rf", name: "Rutherfórdio", atomicNumber: 104, atomicMass: 267, category: "transition-metal", x: 4, y: 7 },
  { symbol: "Db", name: "Dúbnio", atomicNumber: 105, atomicMass: 270, category: "transition-metal", x: 5, y: 7 },
  { symbol: "Sg", name: "Seabórgio", atomicNumber: 106, atomicMass: 271, category: "transition-metal", x: 6, y: 7 },
  { symbol: "Bh", name: "Bóhrio", atomicNumber: 107, atomicMass: 270, category: "transition-metal", x: 7, y: 7 },
  { symbol: "Hs", name: "Hássio", atomicNumber: 108, atomicMass: 277, category: "transition-metal", x: 8, y: 7 },
  { symbol: "Mt", name: "Meitnério", atomicNumber: 109, atomicMass: 276, category: "transition-metal", x: 9, y: 7 },
  { symbol: "Ds", name: "Darmstádio", atomicNumber: 110, atomicMass: 281, category: "transition-metal", x: 10, y: 7 },
  { symbol: "Rg", name: "Roentgênio", atomicNumber: 111, atomicMass: 280, category: "transition-metal", x: 11, y: 7 },
  { symbol: "Cn", name: "Copernício", atomicNumber: 112, atomicMass: 285, category: "transition-metal", x: 12, y: 7 },
  { symbol: "Nh", name: "Nihônio", atomicNumber: 113, atomicMass: 284, category: "post-transition", x: 13, y: 7 },
  { symbol: "Fl", name: "Fleróvio", atomicNumber: 114, atomicMass: 289, category: "post-transition", x: 14, y: 7 },
  { symbol: "Mc", name: "Moscóvio", atomicNumber: 115, atomicMass: 288, category: "post-transition", x: 15, y: 7 },
  { symbol: "Lv", name: "Livermório", atomicNumber: 116, atomicMass: 293, category: "post-transition", x: 16, y: 7 },
  { symbol: "Ts", name: "Tennesso", atomicNumber: 117, atomicMass: 294, category: "halogen", x: 17, y: 7 },
  { symbol: "Og", name: "Oganésson", atomicNumber: 118, atomicMass: 294, category: "noble-gas", x: 18, y: 7 },
];

export const CATEGORY_COLORS: Record<string, string> = {
  "alkali-metal": "bg-red-200 border-red-400 text-red-900",
  "alkaline-earth": "bg-orange-200 border-orange-400 text-orange-900",
  "transition-metal": "bg-yellow-100 border-yellow-300 text-yellow-900",
  "post-transition": "bg-green-200 border-green-400 text-green-900",
  "metalloid": "bg-teal-200 border-teal-400 text-teal-900",
  "nonmetal": "bg-blue-200 border-blue-400 text-blue-900",
  "halogen": "bg-indigo-200 border-indigo-400 text-indigo-900",
  "noble-gas": "bg-purple-200 border-purple-400 text-purple-900",
  "lanthanide": "bg-pink-200 border-pink-400 text-pink-900",
  "actinide": "bg-rose-200 border-rose-400 text-rose-900",
};

export const CATEGORY_NAMES: Record<string, string> = {
  "alkali-metal": "Metais Alcalinos",
  "alkaline-earth": "Metais Alcalino-terrosos",
  "transition-metal": "Metais de Transição",
  "post-transition": "Metais Pós-transição",
  "metalloid": "Semimetais",
  "nonmetal": "Ametais",
  "halogen": "Halogênios",
  "noble-gas": "Gases Nobres",
  "lanthanide": "Lantanídeos",
  "actinide": "Actinídeos",
};
